---
- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - hadolint
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - flake8
        - hadolint
        - python-black
        - yamllint
